title: Chad Currie
tagline: Staff Product Designer
description: Portfolio of Chad Currie, Staff Product Designer.
url: "https://chadcurrie.com"
baseurl: ""

markdown: kramdown
permalink: pretty

nav:
  - title: About
    url: /
  - title: Case Study 1
    url: /case-study-1/
  - title: Case Study 2
    url: /case-study-2/

exclude:
  - README.md
